[project]
name = "mesa"
version = "0.1.0"
description = "Add a short description here"
authors = ["GondekNP <npg@berkeley.edu>"]
channels = ["main", "r", "msys2", "conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]

[target.linux-64.dependencies]
python = "3.11.*"
debugpy = "*"
ipython = "*"
python-dotenv = "*"
planetary-computer = "*"
pystac-client = "*"
scipy = "*"
numpy = "1.24.*"
pandas = "*"
stackstac = "*"
geopandas = "*"
rioxarray = "*"
rasterio = "1.3.*"
networkx = "3.3"
matplotlib = "*"
typing-extensions = ">=4.12.0rc1"
sqlite = "*"
pip = "*"

[target.linux-64.pypi-dependencies]
mesa = { version = "==3.1.0" }
mesa-geo = { version = "==0.9.0a1" }
solara = "*"
