name: mesa
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - debugpy
  - ipython
  - python-dotenv
  - scipy
  - numpy
  - pandas
  - solara
  - sqlite
  - networkx
  - matplotlib
  - typing-extensions >= 4.12.0rc1
  - pip:
      - mesa >= 3.0.3
      - mesa-geo
