name: mesa
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - debugpy
  - ipython
  - python-dotenv
  - scipy
  - numpy
  - pandas
  - solara
  - sqlite
  - typing-extensions >= 4.12.0rc1
  - pip:
      - mesa
      - mesa-geo >= 0.9.0a1
