name: mesa
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - debugpy
  - ipython
  - python-dotenv
  - planetary-computer
  - pystac-client
  - scipy
  - numpy
  - pandas
  - sqlite
  - stackstac
  - geopandas
  - rioxarray
  - networkx
  - matplotlib
  - typing-extensions >= 4.12.0rc1
  - pip:
      - mesa
      - mesa-geo
      - solara
